# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin
# snap apps luncher show in kde when use zsh as main shell
emulate sh -c 'source /etc/profile'
# start tmux when open xterm or uxtermt
# alias xterm="xterm -e tmux"
# alias uxterm="uxterm -e tmux"
export TOOLS_PATH=~/tools
export WORK_PATH=~/work
export GIT_PATH=~/work/git
